name: OWASP Dependency-Check
inputs:
  project:
    required: true
  path:
    required: true
  format:
    required: true
  out:
    required: false
    default: reports
  suppression:
    required: false
runs:
  using: composite
  steps:
    - name: Run OWASP Dependency-Check
      uses: tarsilla-app/actions/code-analysis/base/owasp/owasp@main
      with:
        project: ${{ inputs.project }}
        path: ${{ inputs.path }}
        format: ${{ inputs.format }}
        out: ${{ inputs.out }}
        suppression: ${{ inputs.suppression }}
    - name: Upload OWASP report
      uses: actions/upload-artifact@master
      with:
        name: OWASP report
        path: ${{ github.workspace }}/${{ inputs.out }}