name: NPM Publish
inputs:
  token:
    required: true
  install:
    required: false
    default: npm ci
  build:
    required: false
    default: npm run build
  publish:
    required: false
    default: npx semantic-release 
runs:
  #permissions:
  #  contents: write # to be set in workflow run
  #  id-token: write # to be set in workflow run
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: https://registry.npmjs.org
    - name: Install
      shell: bash
      run: ${{ inputs.install }}
    - name: Build
      shell: bash
      run: ${{ inputs.build }}
    - name: Publish to NPM
      shell: bash
      run: ${{ inputs.publish }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        NPM_TOKEN: ${{ inputs.token }}
