name: NodeJS Publish
inputs:
  config:
    required: true
runs:
  using: composite
  steps:
    - name: Validate config
      run: node validate-config.js
      shell: bash
      env:
        CONFIG: ${{ inputs.config }}

    - id: brew
      if: ${{ fromJson(inputs.config).brew }}
      uses: tarsilla-app/actions/publish/base/brew@main
      with:
        tap: ${{ fromJson(inputs.config).brew.tap }}