name: NodeJS Publish
inputs:
  config:
    required: true
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout reusable action repository
      uses: actions/checkout@v4
      with:
        repository: tarsilla-app/actions
        ref: main
        path: tarsilla-app-actions

    - name: Validate config
      run: node ./tarsilla-app-actions/publish/static/validate-config.js
      shell: bash
      env:
        CONFIG: ${{ inputs.config }}

    - id: brew
      if: ${{ fromJson(inputs.config).brew }}
      uses: tarsilla-app/actions/publish/base/brew@main
      with:
        formula_file: ${{ fromJson(inputs.config).brew.formula_file }}