name: Publish Library
description: Github action to publish library as part of a github workflow for NodeJS projects
inputs:
  publish:
    required: true
  npm-token:
    required: false
  install:
    required: false
  build:
    required: false
  publish:
    required: false
runs:
  using: composite
  steps:
    - id: check publish
      name: Check if publish is needed
      run: 'echo "${{ inputs.publish }}"'
    - id: npm
      if: ${{ inputs.publish == 'npm' }}
      name: Publish Library to NPM
      uses: tarsilla-app/actions/publish/base/npm@main
      with:
        token: ${{ inputs.npm-token }}
        path: ${{ inputs.path }}
        install: ${{ inputs.install }}
        build: ${{ inputs.build }}