name: Deploy Storybook
inputs:
  host:
    required: true
  install:
    required: false
    default: npm ci
  build:
    required: false
    default: npm run build-storybook
  path:
    required: false
    default: storybook-static
outputs:
  pages_url:
    value: ${{ steps.github-pages.outputs.pages_url }}
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: https://registry.npmjs.org
    - id: github-pages
      if: ${{ inputs.host == 'github-pages' }}
      name: Deploy Storybook to Github Pages
      uses: tarsilla-app/actions/deploy/base/github-pages@main
      with:
        install: ${{ inputs.install }}
        build: ${{ inputs.build }}
        path: ${{ inputs.path }}