name: Deploy Storybook to Github Pages
description: Github action to deploy storybook to github pages as part of a github workflow for NodeJS projects
inputs:
  path:
    required: false
    default: storybook-static
  install:
    required: false
    default: npm ci
  build:
    required: false
    default: npm run build-storybook
outputs:
  page_url:
    description: The URL of the page
    value: ${{ steps.deploy.outputs.page_url }}
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: https://registry.npmjs.org
    - id: deploy
      name: Deploy Storybook to Github Pages
      uses: tarsilla-app/actions/deploy/github-pages/base@main
      with:
        path: ${{ inputs.path }}
        install: ${{ inputs.install }}
        build: ${{ inputs.build }}
    - name: Debug Outputs
      run: echo "Page URL Storybook: ${{ steps.deploy.outputs.page_url }}"