name: Deploy
inputs:
  config:
    required: true
  install:
    required: false
  build:
    required: false
  path:
    required: false
outputs:
  pages_url:
    value: ${{ steps.storybook.outputs.pages_url }}
runs:
  using: composite
  steps:
    - id: storybook
      if: ${{ fromJson(inputs.config).type == 'storybook' }}
      uses: tarsilla-app/actions/deploy/storybook@main
      with:
        host: ${{ fromJson(inputs.config).host }}
        install: ${{ inputs.install }}
        build: ${{ inputs.build }}
        path: ${{ inputs.path }}