name: Deploy Storybook
inputs:
  host:
    required: true
  install:
    required: false
    default: npm ci
  build:
    required: false
    default: npm run build-storybook
  path:
    required: false
    default: storybook-static
outputs:
  github_pages_url:
    value: ${{ steps.github-pages.outputs.github_pages_url }}
runs:
  using: composite
  steps:
    - id: github-pages
      if: ${{ inputs.host == 'github-pages' }}
      name: Deploy Storybook to Github Pages
      uses: tarsilla-app/actions/deploy/base/github-pages@main
      with:
        install: ${{ inputs.install }}
        build: ${{ inputs.build }}
        path: ${{ inputs.path }}