name: OWASP Dependency-Check
description: Github action to execute OWASP dependency check as part of a github workflow for NodeJS projects
inputs:
  suppression:
    required: false
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: https://registry.npmjs.org
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Run OWASP Dependency-Check
      uses: tarsilla-app/actions/code-analysis/base/owasp@main
      with:
        project: ${{ github.repository }}
        path: .
        format: HTML
        out: reports
        suppression: ${{ inputs.suppression }}