name: NodeJS Publish
inputs:
  formula_file:
    required: false
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: https://registry.npmjs.org
    
    - name: Install dependencies
      run: npm install @octokit/rest conventional-commits-parser semver
      shell: bash

    - id: get-formula-file-name
      run: node ./tarsilla-app-actions/publish/base/brew/get-formula-file-name.js
      shell: bash
      env:
        REPOSITORY: ${{ github.repository }}
        FORMULA_FILE: ${{ inputs.formula_file }}

    - id: get-next-tag
      run: node ./tarsilla-app-actions/publish/base/brew/get-next-tag.js
      shell: bash
      env:
        REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
        BRANCH: ${{ github.ref_name }}

    - id: update-formula-file-url
      if: ${{ steps.get-next-tag.outputs.nextTag }}
      run: node ./tarsilla-app-actions/publish/base/brew/update-formula-file-url.js
      shell: bash
      env:
        REPOSITORY: ${{ github.repository }}
        FORMULA_FILE_NAME: ${{ steps.get-formula-file-name.outputs.formulaFileName }}
        NEXT_TAG: ${{ steps.get-next-tag.outputs.nextTag }}

    - id: create-tag
      if: ${{ steps.get-next-tag.outputs.nextTag }}
      run: node ./tarsilla-app-actions/publish/base/brew/create-tag.js
      shell: bash
      env:
        NEXT_TAG: ${{ steps.get-next-tag.outputs.nextTag }}

    - id: calculate-sha256
      if: ${{ steps.get-next-tag.outputs.nextTag }}
      run: node ./tarsilla-app-actions/publish/base/brew/calculate-sha256.js
      shell: bash
      env:
        REPOSITORY: ${{ github.repository }}
        NEXT_TAG: ${{ steps.get-next-tag.outputs.nextTag }}

    - id: update-formula-file-sha256
      if: ${{ steps.get-next-tag.outputs.nextTag }}
      run: node ./tarsilla-app-actions/publish/base/brew/update-formula-file-sha256.js
      shell: bash
      env:
        FORMULA_FILE_NAME: ${{ steps.get-formula-file-name.outputs.formulaFileName }}
        SHA256: ${{ steps.calculate-sha256.outputs.sha256 }}

    - id: push-all
      if: ${{ steps.get-next-tag.outputs.nextTag }}
      run: node ./tarsilla-app-actions/publish/base/brew/push-all.js
      shell: bash