name: Publish
inputs:
  config:
    required: true
  npm-token:
    required: false
  install:
    required: false
  build:
    required: false
  publish:
    required: false
runs:
  using: composite
  steps:
    - id: library
      if: ${{ fromJson(inputs.config).type == 'library' }}
      uses: tarsilla-app/actions/publish/library@main
      with:
        repository: ${{ fromJson(inputs.config).repository }}
        npm-token: ${{ secrets.npm-token }}
        install: ${{ inputs.install }}
        build: ${{ inputs.build }}
        publish: ${{ inputs.publish }}