name: OWASP Dependency-Check
inputs:
  project:
    required: true
  path:
    required: true
  format:
    required: true
  out:
    required: false
    default: reports
  suppression:
    required: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.project }}
    - ${{ inputs.path }}
    - ${{ inputs.format }}
    - ${{ inputs.out }}
    - ${{ inputs.suppression }}