name: Snyk Code Test
inputs:
  token:
    required: true
runs:
  using: composite
  steps:
    - name: Run Snyk Code Test
      uses: snyk/actions/node@master
      with:
        command: code test
        args: --severity-threshold=high
      env:
        SNYK_TOKEN: ${{ inputs.token }}