name: NodeJS Publish
inputs:
  config:
    required: true
  node-version:
    required: false
    default: '22.x'
  npm-token:
    required: false
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate config
      run: node ./publish/base/brew/validate-config.js
      shell: bash
      env:
        CONFIG: ${{ inputs.config }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org

    - id: npm
      if: ${{ fromJson(inputs.config).npm }}
      uses: tarsilla-app/actions/publish/base/npm@main
      with:
        token: ${{ inputs.npm-token }}
        install: ${{ fromJson(inputs.config).npm.install || 'npm ci' }}
        build: ${{ fromJson(inputs.config).npm.build || 'npm run build' }}
        publish: ${{ fromJson(inputs.config).npm.publish || 'npx semantic-release' }}