name: NodeJS Publish
description: Publish a new release to NPM when a new tag is created on the repository.
inputs:
  config:
    required: true
  node-version:
    required: false
    default: '25.x'
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout reusable action repository
      uses: actions/checkout@v4
      with:
        repository: tarsilla-app/actions
        ref: main
        path: tarsilla-app-actions

    - name: Validate config
      run: node ./tarsilla-app-actions/publish/validate-config.js
      shell: bash
      env:
        CONFIG: ${{ inputs.config }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org

    - id: npm
      if: ${{ fromJson(inputs.config).npm }}
      uses: tarsilla-app/actions/publish/base/npm@main
      with:
        install: ${{ fromJson(inputs.config).npm.install || 'npm ci' }}
        build: ${{ fromJson(inputs.config).npm.build || 'npm run build' }}
        publish: ${{ fromJson(inputs.config).npm.publish || 'npx semantic-release' }}