name: NodeJS CI/CD
on:
  workflow_call:
    inputs:
      config:
        required: false
        type: string
      node-version:
        required: false
        type: string
        default: '22.x'
    secrets:
      snyk-token:
        required: false
jobs:
  validate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Config
        run: |
          node -e "
          try {
            JSON.parse(process.env.CONFIG);
          } catch (e) {
            console.error('Invalid JSON in inputs.config:', process.env.CONFIG);
            console.error('Error:', e.message);
            process.exit(1);
          }"
        shell: bash
        env:
          CONFIG: ${{ inputs.config }}
  snyk-test:
    runs-on: ubuntu-latest
    needs: [validate-config]
    if: ${{ fromJson(inputs.config).snyk && contains(fromJson(inputs.config).snyk, 'test') }}
    steps:
      - name: validate snyk token
        run: |
          if [ -z "${{ secrets.snyk-token }}" ]; then
            echo "Snyk token is not set. Skipping Snyk Test"
            exit 0
          fi
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - name: Run Snyk Test
        uses: tarsilla-app/actions/code-analysis/base/snyk/test/node@main
        with:
          project: ${{ github.repository }}
          token: ${{ secrets.snyk-token }}
  owasp:
    runs-on: ubuntu-latest
    needs: [validate-config]
    if: ${{ fromJson(inputs.config).owasp }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - name: Run OWASP Test
        uses: tarsilla-app/actions/code-analysis/base/owasp@main
        with:
          project: ${{ github.repository }}
          path: .
          format: HTML
          out: reports
          suppression: ${{ fromJson(inputs.config).owasp.suppression || 'false' }}
  snyk-code-test:
    runs-on: ubuntu-latest
    needs: [validate-config]
    if: ${{ fromJson(inputs.config).snyk && contains(fromJson(inputs.config).snyk, 'code-test') }}
    steps:
      - name: validate snyk token
        run: |
          if [ -z "${{ secrets.snyk-token }}" ]; then
            echo "Snyk token is not set. Skipping Snyk Code Test"
            exit 0
          fi
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - name: Run Snyk Code Test
        uses: tarsilla-app/actions/code-analysis/base/snyk/code-test/node@main
        with:
          token: ${{ secrets.snyk-token }}
  codeql:
    runs-on: ubuntu-latest
    needs: [validate-config]
    if: ${{ fromJson(inputs.config).codeql }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - name: Run Codeql
        uses: tarsilla-app/actions/code-analysis/base/codeql@main
        with:
          languages: javascript-typescript
          build-mode: none
          out: reports